from __future__ import annotations

import json
import math
import re
from typing import List, Literal, Optional

from langchain_core.documents import Document
from langchain_core.tools import tool
from simpleeval import simple_eval

from pathlib import Path

from src.config import CHROMA_PERSIST_DIR, TAVILY_API_KEY, TAVILY_MAX_RESULTS
from src.retrieval.retrieval import hybrid_search


SAFE_MATH_PATTERN = re.compile(r"^[0-9\.\+\-\*\/%\(\),\s_a-zA-Z]+$")
FINANCIAL_KEYWORDS = (
    "net sales",
    "cash flow",
    "revenue",
    "margin",
    "income",
    "profit",
    "sales",
    "eps",
)
FINANCIAL_KEYWORDS_SORTED = sorted(
    FINANCIAL_KEYWORDS,
    key=len,
    reverse=True,
)


METRIC_SYNONYMS: dict[str, list[str]] = {
    "net sales": ["net sales", "total net sales", "revenue", "net revenue"],
    "revenue": ["revenue", "net sales", "total revenue", "net revenue"],
    "gross margin": ["gross margin", "gross profit"],
    "operating income": ["operating income", "income from operations", "operating profit"],
    "operating cash flow": [
        "operating cash flow",
        "cash generated by operating activities",
        "net cash from operating activities",
    ],
    "net income": ["net income", "net earnings", "profit for the period"],
    "eps": ["eps", "earnings per share", "diluted eps", "diluted earnings per share"],
}


def _normalize_metric(metric: str) -> str:
    lowered = " ".join((metric or "").lower().split())
    for canonical, synonyms in METRIC_SYNONYMS.items():
        if lowered in synonyms:
            return canonical
    return lowered


def _match_target_row(
    target_metric: str,
    candidate_tables: list[dict],
    table_rows_path: Path | None = None,
) -> list[dict]:
    """Rule-based row pre-selection from table_rows.jsonl."""
    try:
        path = table_rows_path or (Path(CHROMA_PERSIST_DIR) / "table_rows.jsonl")
        if not path.exists():
            return []

        all_rows: list[dict] = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    all_rows.append(json.loads(line))

        if not all_rows:
            return []

        table_chunk_ids = {
            t.get("chunk_id") for t in candidate_tables if t.get("chunk_id") is not None
        }
        filtered = [r for r in all_rows if r.get("chunk_id") in table_chunk_ids] if table_chunk_ids else all_rows

        normalized_target = _normalize_metric(target_metric)
        synonyms = METRIC_SYNONYMS.get(normalized_target, [normalized_target])

        scored: list[dict] = []
        for row in filtered:
            label = row.get("row_label_normalized", "")
            if label == normalized_target:
                score = 3
            elif normalized_target in label:
                score = 2
            elif any(syn in label for syn in synonyms):
                score = 1
            else:
                continue
            scored.append({**row, "score": score})

        scored.sort(key=lambda r: r["score"], reverse=True)
        return scored[:3]
    except Exception:
        return []


def _compact_text(text: str, max_chars: int = 1400) -> str:
    compact = " ".join((text or "").split())
    if len(compact) <= max_chars:
        return compact
    return compact[:max_chars].rstrip() + "..."


def _citation(document: Document) -> str:
    metadata = document.metadata or {}
    source = metadata.get("source", metadata.get("doc_source", "N/A"))
    page = metadata.get("page", "N/A")
    section = metadata.get("section", "N/A")
    return f"{source} | page {page} | section {section}"


def _looks_like_table(document: Document) -> bool:
    metadata = document.metadata or {}
    category = str(metadata.get("category", "")).lower()
    chunk_kind = str(metadata.get("chunk_kind", "")).lower()
    element_type = str(metadata.get("element_type", "")).lower()

    return (
        "table" in category
        or "table_aligned" in category
        or chunk_kind == "table_aligned"
        or element_type == "table"
    )


def _financial_rank(doc: Document, query: str) -> int:
    metadata = doc.metadata or {}
    score = 0

    metadata_values = [
        str(metadata.get("category", "")).lower(),
        str(metadata.get("element_type", "")).lower(),
        str(metadata.get("chunk_kind", "")).lower(),
    ]
    if "table_aligned" in " ".join(metadata_values):
        score += 15
    elif any("table" in value or "statement" in value for value in metadata_values):
        score += 3

    section = str(metadata.get("section", "")).lower()
    if "consolidated statements of operations" in section:
        score += 5

    query_lower = query.lower()
    text = (doc.page_content or "").lower()
    years = re.findall(r"\b(?:19|20)\d{2}\b", query)
    matched_years = {year for year in years if year in text}
    score += 5 * len(matched_years)
    if years and len(matched_years) == len(set(years)):
        score += 5

    matched_keywords: list[str] = []
    for keyword in FINANCIAL_KEYWORDS_SORTED:
        if keyword not in query_lower and keyword not in text:
            continue
        if any(keyword in prior for prior in matched_keywords):
            continue
        matched_keywords.append(keyword)
        score += 3

    return score


def _select_financial_evidence(
    docs: List[Document],
    query: str,
    max_tables: int = 3,
    max_narrative: int = 2,
) -> List[Document]:
    """Select 2-3 table docs + 1-2 narrative docs from ranked candidates."""
    ranked = sorted(docs, key=lambda doc: _financial_rank(doc, query), reverse=True)
    tables: List[Document] = []
    narratives: List[Document] = []
    for doc in ranked:
        if _looks_like_table(doc) and len(tables) < max_tables:
            tables.append(doc)
        elif not _looks_like_table(doc) and len(narratives) < max_narrative:
            narratives.append(doc)
        if len(tables) >= max_tables and len(narratives) >= max_narrative:
            break
    # Ensure at least 2 tables when available
    if len(tables) < 2:
        for doc in ranked:
            if _looks_like_table(doc) and doc not in tables:
                tables.append(doc)
                if len(tables) >= 2:
                    break
    # Ensure at least 1 narrative when available
    if not narratives:
        for doc in ranked:
            if not _looks_like_table(doc) and doc not in narratives:
                narratives.append(doc)
                break
    return tables + narratives


def _format_docs(
    docs: List[Document],
    mode: Literal["financial", "narrative", "auto"],
    years_requested: list[str] | None = None,
    retrieval_diagnostics: dict | None = None,
    row_candidates: list[dict] | None = None,
) -> str:
    if not docs:
        if mode == "financial":
            payload: object = {
                "search_mode": "financial (dynamically re-ranked)",
                "years_requested": years_requested or [],
                "candidate_tables": [],
                "supporting_narrative": [],
                "row_candidates": row_candidates or [],
                "retrieval_diagnostics": retrieval_diagnostics or {},
            }
        else:
            payload = {
                "search_mode": mode,
                "results": [],
                "retrieval_diagnostics": retrieval_diagnostics or {},
            }
        return json.dumps(payload, indent=2)

    results = []
    for document in docs:
        metadata = document.metadata or {}
        category = (
            metadata.get("category")
            or metadata.get("element_type")
            or metadata.get("chunk_kind")
        )
        content = document.page_content if _looks_like_table(document) else _compact_text(document.page_content)
        results.append(
            {
                "source": metadata.get("source", metadata.get("doc_source", "N/A")),
                "page": metadata.get("page", "N/A"),
                "section": metadata.get("section", "N/A"),
                "category": category,
                "chunk_id": metadata.get("chunk_id"),
                "content": content,
            }
        )

    if mode == "financial":
        candidate_tables = []
        supporting_narrative = []
        for document, item in zip(docs, results):
            if _looks_like_table(document):
                candidate_tables.append(
                    {
                        **item,
                        "content": document.page_content,
                    }
                )
            else:
                supporting_narrative.append(item)
        return json.dumps(
            {
                "search_mode": "financial (dynamically re-ranked)",
                "years_requested": years_requested or [],
                "candidate_tables": candidate_tables,
                "supporting_narrative": supporting_narrative,
                "row_candidates": row_candidates or [],
                "retrieval_diagnostics": retrieval_diagnostics or {},
            },
            indent=2,
        )

    return json.dumps(
        {
            "search_mode": mode,
            "results": results,
            "retrieval_diagnostics": retrieval_diagnostics or {},
        },
        indent=2,
    )


@tool("search_10k", return_direct=False)
def search_10k(query: str, mode: Literal["financial", "narrative", "auto"] = "auto") -> str:
    """
    Hybrid retrieval over ingested 10-K chunks.

    Modes:
    - financial: use lower recall (`k=3`) for exact metric lookups and table-backed values.
    - narrative: use broader recall (`k=6`) for qualitative sections and prose.
    - auto: default broad retrieval (`k=6`) when the caller is unsure.
    """
    resolved_mode = mode
    lowered_query = query.lower()
    years = re.findall(r"\b(?:19|20)\d{2}\b", query)

    if resolved_mode == "auto":
        if any(keyword in lowered_query for keyword in FINANCIAL_KEYWORDS) or years:
            resolved_mode = "financial"
        else:
            resolved_mode = "narrative"

    if resolved_mode == "financial":
        docs, debug_info = hybrid_search(query=query, k=10, weights=(0.5, 0.5), return_debug=True)
        docs = _select_financial_evidence(docs, query)

        # Extract target metric from query for row pre-selection
        target_metric = ""
        for keyword in FINANCIAL_KEYWORDS_SORTED:
            if keyword in lowered_query:
                target_metric = keyword
                break

        # Build table refs from selected evidence for _match_target_row
        candidate_tables = [
            {"chunk_id": doc.metadata.get("chunk_id")}
            for doc in docs
            if _looks_like_table(doc) and doc.metadata.get("chunk_id") is not None
        ]
        row_candidates = _match_target_row(target_metric, candidate_tables) if target_metric else []

        return _format_docs(
            docs,
            mode=resolved_mode,
            years_requested=years,
            retrieval_diagnostics=debug_info,
            row_candidates=row_candidates,
        )
    else:
        docs, debug_info = hybrid_search(query=query, k=6, weights=(0.5, 0.5), return_debug=True)

    return _format_docs(docs, mode=resolved_mode, years_requested=years, retrieval_diagnostics=debug_info)


@tool("yfinance_tool", return_direct=False)
def yfinance_tool(ticker: str) -> str:
    """
    Fetch a market snapshot for a public ticker using yfinance.
    Returns current price, valuation metrics, and recent price context.
    """
    symbol = ticker.strip().upper()
    if not symbol:
        return "Provide a ticker symbol, for example AAPL or MSFT."

    try:
        import yfinance as yf
    except ImportError:
        return "yfinance is not installed. Add `yfinance` to requirements."

    try:
        security = yf.Ticker(symbol)
        info = getattr(security, "info", {}) or {}
        fast_info = getattr(security, "fast_info", {}) or {}
        history = security.history(period="1mo", interval="1d")

        latest_close = None
        month_change_pct = None
        if history is not None and not history.empty:
            latest_close = float(history["Close"].iloc[-1])
            first_close = float(history["Close"].iloc[0])
            if first_close:
                month_change_pct = ((latest_close - first_close) / first_close) * 100.0

        snapshot = {
            "ticker": symbol,
            "company_name": info.get("shortName") or info.get("longName"),
            "currency": info.get("currency") or fast_info.get("currency"),
            "current_price": info.get("currentPrice") or fast_info.get("lastPrice") or latest_close,
            "previous_close": info.get("previousClose") or fast_info.get("previousClose"),
            "market_cap": info.get("marketCap"),
            "trailing_pe": info.get("trailingPE"),
            "forward_pe": info.get("forwardPE"),
            "dividend_yield": info.get("dividendYield"),
            "volume": info.get("volume") or fast_info.get("lastVolume"),
            "fifty_two_week_high": info.get("fiftyTwoWeekHigh") or fast_info.get("yearHigh"),
            "fifty_two_week_low": info.get("fiftyTwoWeekLow") or fast_info.get("yearLow"),
            "one_month_change_pct": round(month_change_pct, 4) if month_change_pct is not None else None,
        }
        return json.dumps(snapshot, indent=2, default=str)
    except Exception as exc:
        return f"yfinance lookup failed for {symbol}: {exc}"


@tool("calculator", return_direct=False)
def calculator(expression: str) -> str:
    """
    Deterministic calculator for financial arithmetic.
    Accepts raw arithmetic expressions only.
    """
    cleaned = expression.strip()
    if not cleaned:
        return "Provide a math expression, for example (391035-383285)/383285*100."
    if not SAFE_MATH_PATTERN.fullmatch(cleaned):
        return "Unsupported characters in expression."

    normalized = cleaned.replace("^", "**")
    try:
        import numexpr as ne

        result = ne.evaluate(normalized, global_dict={}, local_dict={})
        if hasattr(result, "item"):
            result = result.item()
        return str(result)
    except ImportError:
        math_functions = {name: getattr(math, name) for name in dir(math) if not name.startswith("_")}
        try:
            return str(simple_eval(normalized, functions=math_functions))
        except Exception as exc:
            return f"Error processing calculation: {exc}"
    except Exception as exc:
        return f"Error processing calculation: {exc}"


@tool("web_search", return_direct=False)
def web_search(query: str) -> str:
    """
    Search macroeconomic or market news using Tavily.
    """
    if not query.strip():
        return "Provide a search query."
    if not TAVILY_API_KEY:
        return "TAVILY_API_KEY is not set."

    try:
        from tavily import TavilyClient
    except ImportError:
        return "tavily-python is not installed. Add `tavily-python` to requirements."

    try:
        client = TavilyClient(api_key=TAVILY_API_KEY)
        response = client.search(query=query, max_results=TAVILY_MAX_RESULTS)
        results = response.get("results", [])
        if not results:
            return "No web results found."

        formatted = []
        for index, item in enumerate(results, start=1):
            formatted.append(
                f"[{index}] {item.get('title', 'Untitled')}\n"
                f"url: {item.get('url', 'N/A')}\n"
                f"{_compact_text(item.get('content', ''), max_chars=600)}"
            )
        return "\n\n---\n\n".join(formatted)
    except Exception as exc:
        return f"Tavily search failed: {exc}"


TOOLS = [search_10k, yfinance_tool, calculator, web_search]


if __name__ == "__main__":
    print("Loaded tools:")
    for tool_obj in TOOLS:
        print(f"- {tool_obj.name}")
